version: '3.8'

services:
  database:
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE = ${MONGO_DATABASE}