version: '3.8'

services:
  database:
    container_name: database
    image: mongo:7.0.5
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE = ${MONGO_DATABASE}
    ports:
      - 27018:27017
    volumes:
      - database:/app/data
    networks:
      - network-despliegue


volumes:
  database:

networks:
  network-despliegue:
    driver: bridge